version: "3.1"
services:
  bokuto:
    image: bokuto
    build:
      context: .
    environment:
    - NODE_ENV=local
    - EVENTS_TABLE=dev-bokuto-events
    - SESSION_SECRET=docker
    - EXTERNAL_SESSION_SECRET=docker
    - AWS_SDK_LOAD_CONFIG=1
    - AWS_PROFILE=${AWS_PROFILE}
    volumes:
    - ~/.aws/:/root/.aws/:ro
    ports:
    - 3000:3000
